### ISSUE TITLE
Set Up Prisma

### ISSUE THREAD

**Issue by AhmadHRai** [ByteRunners/nextjs-sprout#27]
Prisma is an open-source database toolkit. It replaces traditional ORMs and makes database access easy and enjoyable.

Tasks:

- [x]     Install Prisma and its related dependencies
- [x]     Initialize Prisma in your Next.js project
- [ ]     Configure Prisma to connect to your database
- [ ]     Create a Prisma model and perform some basic operations

[Prisma Documentation](https://www.prisma.io/docs/)
[Prisma with Next.js](https://www.prisma.io/nextjs)

**Comment by nabily4e-dev** [comment]
> @nabily4e-dev we should configure a database for the template before prisma

I would definitely go with postgreSQL!

[Vercel Postgres:](https://vercel.com/guides/nextjs-prisma-postgres) A managed PostgreSQL database service that is fully compatible with Next.js and Prisma. Vercel Postgres provides high availability, scalability, and security for your data. You can easily connect to your database from your Next.js app using environment variables and deploy your changes with zero downtime.

**Comment by nabily4e-dev** [comment]
@AhmadHRai, where are at with this issue?
